/**
 * AccountPreferencesScreen Dark Theme Styles
 * ==========================================
 */

import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B1A1F', // Dark theme
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(20, 184, 166, 0.2)',
  },
  backButton: {
    padding: 4,
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    letterSpacing: -0.3,
  },
  headerSpacer: {
    width: 32,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#0B1A1F',
  },
  content: {
    flex: 1,
    backgroundColor: '#0D2832',
  },
  section: {
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(20, 184, 166, 0.1)',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  field: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '500',
    color: '#B4E4DD',
    marginBottom: 8,
  },
  input: {
    backgroundColor: 'rgba(11, 26, 31, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(20, 184, 166, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#FFFFFF',
  },
  inputDisabled: {
    backgroundColor: 'rgba(11, 26, 31, 0.4)',
    color: '#6B8A84',
    opacity: 0.7,
  },
  fieldNote: {
    fontSize: 12,
    color: '#6B8A84',
    marginTop: 6,
  },
  saveButton: {
    backgroundColor: '#14B8A6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    marginTop: 8,
    shadowColor: '#14B8A6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  saveButtonDisabled: {
    opacity: 0.5,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  dangerSection: {
    padding: 20,
  },
  dangerCard: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  dangerTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#EF4444',
    marginBottom: 8,
  },
  dangerDescription: {
    fontSize: 14,
    color: '#FCA5A5',
    marginBottom: 16,
    lineHeight: 20,
  },
  dangerButton: {
    backgroundColor: '#EF4444',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    borderRadius: 8,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  dangerButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  disabledSection: {
    opacity: 0.5,
  },
  disabledSectionTitle: {
    color: '#6B8A84',
  },
  googleAccountNotice: {
    flexDirection: 'row',
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    gap: 12,
  },
  googleAccountNoticeIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.4)',
  },
  googleAccountNoticeContent: {
    flex: 1,
  },
  googleAccountNoticeTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 6,
  },
  googleAccountNoticeText: {
    fontSize: 13,
    color: '#B4E4DD',
    lineHeight: 19,
    marginBottom: 8,
  },
  googleAccountNoticeLink: {
    fontSize: 12,
    fontWeight: '600',
    color: '#3B82F6',
  },
  // Delete Modal Styles - Dark Theme
  deleteModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  deleteModalContainer: {
    backgroundColor: '#0D2832',
    borderRadius: 20,
    padding: 28,
    width: '100%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: 'rgba(20, 184, 166, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  deleteModalIconContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  deleteModalIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  deleteModalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 6,
    letterSpacing: -0.5,
  },
  deleteModalSubtitle: {
    fontSize: 14,
    color: '#B4E4DD',
    textAlign: 'center',
    marginBottom: 24,
    fontWeight: '500',
  },
  deleteModalWarningBox: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 12,
    padding: 16,
    borderWidth: 2,
    borderColor: 'rgba(239, 68, 68, 0.3)',
    marginBottom: 24,
  },
  deleteModalWarningTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#EF4444',
    marginBottom: 12,
  },
  deleteModalWarningList: {
    gap: 10,
  },
  deleteModalWarningItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  deleteModalWarningText: {
    flex: 1,
    fontSize: 13,
    color: '#FCA5A5',
    lineHeight: 18,
  },
  deleteModalButtons: {
    gap: 10,
  },
  deleteCancelButton: {
    backgroundColor: 'rgba(20, 184, 166, 0.12)',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(20, 184, 166, 0.3)',
  },
  deleteCancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#14B8A6',
  },
  deleteConfirmButton: {
    backgroundColor: '#EF4444',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  deleteConfirmButtonDisabled: {
    opacity: 0.5,
  },
  deleteConfirmButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // Level Selector Styles - Dark Theme
  levelSelector: {
    backgroundColor: 'rgba(11, 26, 31, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(20, 184, 166, 0.2)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  levelSelectorContent: {
    flex: 1,
    marginRight: 12,
  },
  levelSelectorText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  levelSelectorDescription: {
    fontSize: 13,
    color: '#B4E4DD',
    lineHeight: 18,
  },
  // Level Picker Modal Styles - Dark Theme
  levelPickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'flex-end',
  },
  levelPickerContainer: {
    backgroundColor: '#0D2832',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
    paddingHorizontal: 20,
    maxHeight: '80%',
    borderTopWidth: 1,
    borderColor: 'rgba(20, 184, 166, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  levelPickerHeader: {
    marginBottom: 20,
    alignItems: 'center',
  },
  levelPickerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
    letterSpacing: -0.3,
  },
  levelPickerSubtitle: {
    fontSize: 14,
    color: '#B4E4DD',
    textAlign: 'center',
  },
  levelPickerScroll: {
    marginBottom: 16,
  },
  levelOption: {
    backgroundColor: 'rgba(11, 26, 31, 0.6)',
    borderWidth: 2,
    borderColor: 'rgba(20, 184, 166, 0.2)',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
  },
  levelOptionSelected: {
    backgroundColor: 'rgba(20, 184, 166, 0.15)',
    borderColor: '#14B8A6',
    shadowColor: '#14B8A6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  levelOptionContent: {
    flex: 1,
  },
  levelOptionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  levelOptionLabel: {
    fontSize: 17,
    fontWeight: '700',
    color: '#B4E4DD',
  },
  levelOptionLabelSelected: {
    color: '#14B8A6',
  },
  levelOptionCheck: {
    marginLeft: 8,
  },
  levelOptionDescription: {
    fontSize: 14,
    color: '#6B8A84',
    lineHeight: 20,
  },
  levelOptionDescriptionSelected: {
    color: '#B4E4DD',
  },
  levelPickerCancelButton: {
    backgroundColor: 'rgba(20, 184, 166, 0.12)',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(20, 184, 166, 0.3)',
  },
  levelPickerCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#14B8A6',
  },
});
