import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B1A1F',
  },
  // iOS-Native Header - Dark Theme Design with Larger Logo
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#0B1A1F',
    paddingHorizontal: 20,
    paddingVertical: 16,
    height: 88,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(20, 184, 166, 0.2)',
  },
  logo: {
    width: SCREEN_WIDTH < 400 ? 140 : 180, // Optimized size for transparent logo
    height: SCREEN_WIDTH < 400 ? 45 : 58, // Maintain aspect ratio
  },
  logoMinimal: {
    width: 75, // Compact bear face logo (50% larger)
    height: 75,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  upgradeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(20, 184, 166, 0.15)',
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: '#14B8A6',
  },
  upgradeButtonText: {
    color: '#14B8A6',
    fontSize: 17,
    fontWeight: '700',
  },
  // Compact Premium Badge in Header - Dark Theme with Premium Feel
  premiumBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(251, 191, 36, 0.15)', // Gold tinted
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.4)',
    shadowColor: '#FBBF24',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  crownEmojiCompact: {
    fontSize: 14,
  },
  premiumTextCompact: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FBBF24', // Gold
    letterSpacing: 0.3,
    lineHeight: 12,
  },
  premiumMinutesCompact: {
    fontSize: 9,
    fontWeight: '600',
    color: '#FCD34D', // Lighter gold
    lineHeight: 10,
  },
  // Compact Free Badge in Header - Dark Theme with Muted Feel
  freeBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(107, 138, 132, 0.15)', // Muted teal
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(107, 138, 132, 0.4)',
    shadowColor: '#6B8A84',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  freeTextCompact: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8CA5A0', // Muted teal text
    letterSpacing: 0.3,
    lineHeight: 12,
  },
  freeMinutesCompact: {
    fontSize: 9,
    fontWeight: '600',
    color: '#6B8A84', // Slightly muted
    lineHeight: 10,
  },
  // Compact Streak Badge in Header - Dark Theme with Glow
  streakBadgeCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(239, 68, 68, 0.15)', // Red tinted
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
    shadowColor: '#EF4444',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 4,
  },
  fireEmojiCompact: {
    fontSize: 16,
  },
  streakNumberCompact: {
    fontSize: 13,
    fontWeight: '700',
    color: '#EF4444', // Bright red
    lineHeight: 14,
  },
  streakLabelCompact: {
    fontSize: 9,
    fontWeight: '600',
    color: '#FCA5A5', // Lighter red
    lineHeight: 10,
  },
  // Notification Bell Badge - Dark Theme with Turquoise Glow
  notificationBell: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: '#0B1A1F',
  },
  notificationCount: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  scrollView: {
    flex: 1,
    backgroundColor: '#0D2832',
  },
  scrollContent: {
    paddingBottom: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    fontSize: 16,
    color: '#B4E4DD',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
    gap: 16,
    backgroundColor: '#0D2832',
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  errorMessage: {
    fontSize: 14,
    color: '#B4E4DD',
    textAlign: 'center',
    lineHeight: 20,
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EF4444',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    gap: 8,
    marginTop: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  emptyContainer: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 30,
    gap: 12,
    backgroundColor: '#0D2832',
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1F2937',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  emptyMessage: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
    fontWeight: '500',
  },
  // Session Cards Container - Rounded Modern Design
  sessionCardsContainer: {
    width: '100%',
    paddingHorizontal: 16,
    gap: 12,
    marginTop: 20,
  },
  sessionCard: {
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  sessionCardGradient: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    minHeight: 150,
    position: 'relative',
  },
  sessionCardContent: {
    position: 'relative',
    zIndex: 1,
  },
  sessionCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  sessionIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 13,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  popularBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 214, 58, 0.3)',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 11,
    gap: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 58, 0.5)',
  },
  popularText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.8,
  },
  sessionCardTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 6,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    letterSpacing: 0.2,
  },
  sessionCardDescription: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.95)',
    lineHeight: 19,
    fontWeight: '500',
    marginBottom: 12,
  },
  sessionFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  featureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 12,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  featureBadgeText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '700',
    letterSpacing: 0.1,
  },
  // Hero Greeting Section - Premium iOS Design
  titleSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    backgroundColor: '#FFFFFF',
    marginBottom: 8,
  },
  greetingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  greetingText: {
    fontSize: SCREEN_HEIGHT < 700 ? 24 : 28,
    fontWeight: '700',
    color: '#1F2937',
  },
  greetingEmoji: {
    fontSize: 28,
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  statBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
  },
  statBadgeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#D97706',
  },
  levelBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#DBEAFE',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
  },
  levelBadgeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1D4ED8',
  },
  // Language Groups Container (Legacy - for CollapsibleLanguageGroup)
  languageGroupsContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  // Grid Container (New - for 2-column grid)
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    paddingTop: 8,
    justifyContent: 'space-between',
  },
  gridItem: {
    marginBottom: 12,
  },
  gridItemLeft: {
    marginRight: 6,
  },
  gridItemRight: {
    marginLeft: 6,
  },
  // Compact Divider
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 4,
    marginBottom: 8,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E5E7EB',
  },
  dividerText: {
    marginHorizontal: 12,
    fontSize: 11,
    color: '#9CA3AF',
    fontWeight: '600',
  },
  // Modern Animated Gradient Button Styles
  newSessionButtonContainer: {
    marginHorizontal: 20,
    marginBottom: 8,
  },
  newSessionButton: {
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#8B5CF6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  newSessionGradient: {
    paddingVertical: 22,
    paddingHorizontal: 24,
    position: 'relative',
    backgroundColor: '#8B5CF6',
  },
  newSessionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    position: 'relative',
    zIndex: 1,
  },
  newSessionIconContainer: {
    position: 'relative',
  },
  iconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  newSessionTextContainer: {
    flex: 1,
  },
  newSessionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  newSessionSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.95)',
    fontWeight: '600',
  },
  arrowContainer: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // New Redesigned Empty State Styles
  welcomeSection: {
    width: '100%',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 20,
    gap: 12,
  },
  premiumBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7',
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    gap: 6,
    marginBottom: 8,
  },
  premiumBadgeText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#D97706',
    letterSpacing: 0.3,
  },
  welcomeTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1F2937',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  welcomeMessage: {
    fontSize: 15,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 22,
    fontWeight: '500',
    paddingHorizontal: 10,
  },
  // Trial Notification Container (Free Users)
  trialNotificationContainer: {
    width: '100%',
    gap: 12,
  },
  trialInfoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#FFE4B3',
    paddingHorizontal: 18,
    paddingVertical: 16,
    gap: 14,
    shadowColor: '#FFA955',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
  },
  trialIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FFA955',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  trialInfoContent: {
    flex: 1,
  },
  trialInfoText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#6B5020',
    lineHeight: 22,
  },
  trialInfoHighlight: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFA955',
  },
  upgradeButtonFull: {
    width: '100%',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  upgradeButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 8,
  },
  upgradeButtonFullText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // ========== NEW FREE USER DESIGN (Following Design Prompt) ==========
  freeUserContainer: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 16,
  },
  // SECONDARY - Freestyle Chat (Solid Turquoise #4ECFBF)
  secondaryCardNew: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#4ECFBF', // Solid turquoise
    borderRadius: 18,
    padding: 20,
    gap: 14,
    borderWidth: 2.5,
    borderColor: '#3AB8A8', // Darker turquoise border
    shadowColor: '#4ECFBF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 8,
  },
  secondaryCardIcon: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2.5,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  secondaryCardText: {
    flex: 1,
  },
  secondaryCardTitleNew: {
    fontSize: 19,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  secondaryCardSubtitle: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  // PRIMARY - Speaking Assessment (Solid Coral #F75A5A)
  primaryCardNew: {
    width: '100%',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#F75A5A',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 2.5,
    borderColor: '#E84545', // Darker coral border
  },
  primaryCardGradientNew: {
    paddingHorizontal: 22,
    paddingVertical: 20,
    minHeight: 160,
    backgroundColor: '#F75A5A', // Solid coral
  },
  primaryCardHeaderNew: {
    alignItems: 'center',
    marginBottom: 14,
  },
  primaryIconContainerNew: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Semi-transparent white
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2.5,
    borderColor: 'rgba(255, 255, 255, 0.4)', // Light border
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  primaryCardTitleNew: {
    fontSize: 22,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 8,
    letterSpacing: 0.3,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  primaryCardDescriptionNew: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
    lineHeight: 20,
    marginBottom: 14,
    textAlign: 'center',
  },
  primaryFeaturesNew: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
    justifyContent: 'center',
    maxWidth: '100%',
  },
  featurePill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Semi-transparent white for contrast
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
    gap: 4,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.35)', // Light border
  },
  featurePillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.1,
  },
  // Usage Limits Banner - Solid Amber Design with Dark Background
  usageLimitsBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF3C7', // Solid light amber background
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
    borderWidth: 2,
    borderColor: '#F59E0B', // Orange border
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  usageLimitsText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#92400E', // Dark brown text for contrast
    flex: 1,
    letterSpacing: 0.2,
  },
  usageLimitsHighlight: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFA955',
  },
  // Upgrade Link - Premium Gold Gradient
  upgradeLinkContainer: {
    borderRadius: 16,
    borderWidth: 2.5,
    borderColor: '#D97706', // Darker gold border
    marginTop: 4,
    shadowColor: '#FBBF24',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 8,
    overflow: 'hidden',
  },
  upgradeLinkInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    paddingHorizontal: 20,
    gap: 12,
  },
  upgradeIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  upgradeLinkText: {
    fontSize: 17,
    fontWeight: '800',
    color: '#FFFFFF',
    flex: 1,
    textAlign: 'center',
    letterSpacing: 0.3,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  // ========== END NEW FREE USER DESIGN ==========

  // ========== PREMIUM USER DESIGN (Scenario 2: Post-Purchase Activation) ==========
  // Clear Premium Status Badge
  premiumStatusBadgeContainer: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
  },
  premiumStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 214, 58, 0.3)',
    shadowColor: '#FFD63A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 3,
    gap: 12,
  },
  premiumStatusIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 214, 58, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FFD63A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  crownEmoji: {
    fontSize: 24,
    lineHeight: 24,
  },
  premiumStatusTextContainer: {
    flex: 1,
  },
  premiumStatusTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFD63A',
    marginBottom: 2,
  },
  premiumStatusSubtitle: {
    fontSize: 13,
    fontWeight: '500',
    color: '#FFC107',
  },
  // Streak Badge Container - For users with learning plans
  streakBadgeContainer: {
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
    alignItems: 'flex-start',
  },
  // Premium User Container
  premiumUserContainer: {
    width: '100%',
    paddingHorizontal: 20,
    gap: 16,
  },
  // PRIMARY CTA - Dominant, Full Focus
  premiumPrimaryCard: {
    width: '100%',
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#4ECFBF',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 12,
  },
  premiumPrimaryGradient: {
    paddingHorizontal: 28,
    paddingVertical: 32,
    alignItems: 'center',
    minHeight: 240,
  },
  premiumPrimaryIconContainer: {
    width: 72,
    height: 72,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  premiumPrimaryTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: -0.3,
    lineHeight: 32,
  },
  premiumPrimarySubtitle: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    marginBottom: 20,
  },
  premiumFeaturePills: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  premiumPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 4,
  },
  premiumPillText: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.95)',
  },
  // Reassurance Section
  reassuranceSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 12,
    paddingHorizontal: 8,
  },
  reassuranceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  reassuranceText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6B7280',
  },
  // SECONDARY CTA - Clearly Optional
  premiumSecondaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 20,
    gap: 10,
    borderWidth: 1.5,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  premiumSecondaryText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#6B7280',
    flex: 1,
  },
  // ========== END PREMIUM USER DESIGN ==========

  // Primary Card - Create Learning Plan (Large, prominent)
  primaryCard: {
    width: '100%',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 8,
    marginTop: 8,
  },
  primaryCardGradient: {
    paddingHorizontal: 24,
    paddingVertical: 24,
    minHeight: 180,
    position: 'relative',
  },
  primaryCardContent: {
    position: 'relative',
    zIndex: 1,
  },
  primaryCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  primaryIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  starBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 214, 58, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 214, 58, 0.5)',
  },
  primaryCardTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    letterSpacing: 0.3,
  },
  primaryCardDescription: {
    fontSize: 15,
    color: 'rgba(255, 255, 255, 0.95)',
    lineHeight: 21,
    fontWeight: '500',
    marginBottom: 16,
  },
  primaryFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  primaryFeatureBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 14,
    gap: 5,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  primaryFeatureBadgeText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  // "Or" divider text
  orText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontWeight: '600',
    textAlign: 'center',
    marginVertical: 16,
  },
  // Secondary Card - Quick Practice (Smaller, less prominent)
  secondaryCard: {
    width: '100%',
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  secondaryCardGradient: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    minHeight: 80,
  },
  secondaryCardContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  secondaryIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.35)',
  },
  secondaryCardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 2,
  },
  secondaryCardDescription: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '500',
  },
  // Bottom info section
  bottomInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 20,
    paddingHorizontal: 20,
  },
  bottomInfoText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  // Premium link
  premiumLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 12,
    paddingVertical: 8,
  },
  premiumLinkText: {
    fontSize: 14,
    color: '#4FD1C5',
    fontWeight: '600',
  },
  // Tip container for subscribed users
  tipContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#FFFBEB',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#FEF3C7',
  },
  tipText: {
    flex: 1,
    fontSize: 13,
    color: '#92400E',
    fontWeight: '500',
    lineHeight: 18,
  },
  // Premium Benefits Modal Styles
  premiumBenefitsContainer: {
    flex: 1,
    backgroundColor: '#0B1A1F',
  },
  premiumBenefitsGradient: {
    flex: 1,
    paddingTop: 60,
  },
  premiumBenefitsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(20, 184, 166, 0.2)',
  },
  premiumBenefitsTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  premiumBenefitsTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  premiumBenefitsCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(31, 41, 55, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  premiumBenefitsScroll: {
    flex: 1,
    paddingHorizontal: 20,
  },
  premiumSubscriptionCard: {
    borderRadius: 16,
    padding: 20,
    marginTop: 20,
    marginBottom: 24,
    borderWidth: 1.5,
    alignItems: 'center',
    // backgroundColor and borderColor applied inline for solid coloring
  },
  premiumSubscriptionPlan: {
    fontSize: 20,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  premiumSubscriptionStatus: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
  },
  premiumBenefitsList: {
    gap: 16,
  },
  premiumBenefitItem: {
    flexDirection: 'row',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    gap: 16,
    // backgroundColor and borderColor applied inline for dynamic coloring
  },
  premiumBenefitIconContainer: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor and borderColor applied inline for dynamic coloring
  },
  premiumBenefitTextContainer: {
    flex: 1,
  },
  premiumBenefitTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  premiumBenefitDescription: {
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 20,
  },
  premiumThankYouCard: {
    borderRadius: 16,
    padding: 24,
    marginTop: 24,
    marginBottom: 40,
    borderWidth: 1.5,
    alignItems: 'center',
    // backgroundColor and borderColor applied inline for dynamic coloring
  },
  premiumThankYouText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  premiumThankYouSubtext: {
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: 20,
  },
  // Badge Glow Effects - Extracted from inline styles
  badgeGlowFree: {
    position: 'absolute',
    top: -2,
    left: -2,
    right: -2,
    bottom: -2,
    borderRadius: 14,
    backgroundColor: 'rgba(107, 138, 132, 0.2)',
    opacity: 0.5,
  },
  badgeGlowPremium: {
    position: 'absolute',
    top: -2,
    left: -2,
    right: -2,
    bottom: -2,
    borderRadius: 14,
    backgroundColor: 'rgba(251, 191, 36, 0.2)',
    opacity: 0.5,
  },
  badgeGlowStreak: {
    position: 'absolute',
    top: -2,
    left: -2,
    right: -2,
    bottom: -2,
    borderRadius: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    opacity: 0.5,
  },
  // Notification Count Badge - Extracted from inline styles
  notificationCountBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 6,
  },
  notificationCountText: {
    fontSize: 11,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: -0.5,
  },
  // Empty Grid State - Extracted from inline styles
  emptyGridContainer: {
    padding: 20,
    alignItems: 'center',
  },
  emptyGridText: {
    color: '#9CA3AF',
    fontSize: 14,
  },

  // ========== NEW USER ONBOARDING EMPTY STATE ==========
  newUserWelcomeSection: {
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 8,
  },
  newUserLottie: {
    width: 160,
    height: 160,
  },
  newUserGreeting: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 4,
  },
  newUserSubtitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#B4E4DD',
    textAlign: 'center',
    marginTop: 6,
  },

  // Primary CTA Card — Coral → Orange gradient
  newUserPrimaryCard: {
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#F75A5A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  newUserPrimaryGradient: {
    paddingHorizontal: 24,
    paddingVertical: 28,
    alignItems: 'center',
  },
  newUserPrimaryIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  newUserPrimaryTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  newUserPrimarySubtitle: {
    fontSize: 15,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.9)',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  newUserPrimaryButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    paddingHorizontal: 40,
    borderRadius: 14,
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  newUserPrimaryButtonText: {
    fontSize: 17,
    fontWeight: '800',
    color: '#F75A5A',
    letterSpacing: 0.3,
  },
  newUserPrimaryMeta: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  newUserMetaBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    gap: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  newUserMetaText: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
  },

  // How It Works Section — 3 cards in a row, all visible
  newUserHowItWorks: {
    marginTop: 28,
    width: '100%',
    paddingHorizontal: 20,
  },
  newUserHowItWorksTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 16,
  },
  newUserStepsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  newUserStepCard: {
    flex: 1,
    borderRadius: 18,
    padding: 14,
    justifyContent: 'flex-start',
  },
  newUserStepCardNumber: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  newUserStepCardNumberText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#FFFFFF',
  },
  newUserStepCardIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  newUserStepCardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#FFFFFF',
    marginBottom: 3,
  },
  newUserStepCardDesc: {
    fontSize: 11,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.8)',
    lineHeight: 15,
  },

  // Secondary Link
  newUserSecondaryLink: {
    marginTop: 24,
    paddingVertical: 12,
    alignItems: 'center',
  },
  newUserSecondaryLinkText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4ECFBF',
  },

  // Soft Upgrade Banner
  newUserUpgradeBanner: {
    marginTop: 20,
    marginHorizontal: 20,
    marginBottom: 30,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 214, 58, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 214, 58, 0.2)',
    alignItems: 'center',
  },
  newUserUpgradeText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFD63A',
    textAlign: 'center',
  },
  // ========== END NEW USER ONBOARDING EMPTY STATE ==========
});
