import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export { width };

export const styles = StyleSheet.create({
  container: {
    marginHorizontal: 0,
    marginBottom: 0,
    borderRadius: 20,
    overflow: 'hidden',
  },
  gradient: {
    borderRadius: 20,
  },
  whiteCard: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    paddingBottom: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
  },
  headerDate: {
    fontSize: 13,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 6,
    marginHorizontal: 3,
    borderWidth: 2,
  },
  statValue: {
    fontSize: 24,
    fontWeight: '900',
    marginBottom: 3,
  },
  statLabel: {
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  progressBarContainer: {
    marginTop: 4,
    marginBottom: 12,
  },
  progressBarBackground: {
    height: 8,
    backgroundColor: '#F3F4F6',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: 8,
  },
  progressBarFill: {
    height: '100%',
    borderRadius: 4,
  },
  progressBarLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
    textAlign: 'center',
  },
  expandableSection: {
    marginTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    paddingTop: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionIcon: {
    fontSize: 16,
    marginRight: 8,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  sectionChevron: {
    fontSize: 12,
    color: '#9CA3AF',
  },
  sectionContent: {
    overflow: 'hidden',
  },
  breakdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    marginTop: 8,
  },
  breakdownLeft: {
    flex: 1,
  },
  breakdownKey: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 2,
  },
  breakdownDetail: {
    fontSize: 11,
    fontWeight: '500',
    color: '#6B7280',
  },
  breakdownRight: {
    alignItems: 'flex-end',
  },
  breakdownAccuracy: {
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 2,
  },
  breakdownXP: {
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  breakdownXPText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#4B5563',
  },
  milestoneContainer: {
    marginTop: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#FEF3C7',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#FCD34D',
  },
  milestoneText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#92400E',
    textAlign: 'center',
  },
  loadingContainer: {
    paddingVertical: 40,
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 12,
  },
  errorContainer: {
    paddingVertical: 30,
    alignItems: 'center',
  },
  errorEmoji: {
    fontSize: 40,
    marginBottom: 10,
  },
  errorTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#EF4444',
    marginBottom: 6,
  },
  errorMessage: {
    fontSize: 13,
    fontWeight: '500',
    color: '#6B7280',
    textAlign: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: '#4ECFBF',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 10,
  },
  retryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  emptyState: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  emptyEmoji: {
    fontSize: 40,
    marginBottom: 10,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E40AF',
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: 13,
    fontWeight: '500',
    color: '#3B82F6',
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  emptyStreakInfo: {
    fontSize: 12,
    fontWeight: '600',
    color: '#DC2626',
    textAlign: 'center',
    marginTop: 8,
    paddingHorizontal: 20,
  },
  // Motivational Banner Styles
  motivationalBanner: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  bannerHeader: {
    position: 'relative',
    marginBottom: 12,
  },
  streakBadge: {
    position: 'absolute',
    top: -4,
    right: -8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#DC2626',
  },
  streakNumber: {
    fontSize: 11,
    fontWeight: '900',
    color: '#DC2626',
  },
  bannerTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: '#115E59',
    textAlign: 'center',
    marginBottom: 6,
  },
  bannerSubtitle: {
    fontSize: 13,
    fontWeight: '500',
    color: '#134E4A',
    textAlign: 'center',
    marginBottom: 14,
    lineHeight: 18,
  },
  bannerPerks: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 12,
    marginBottom: 12,
  },
  perkItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  perkText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0F766E',
  },
  perkDivider: {
    width: 1,
    height: 12,
    backgroundColor: 'rgba(15, 118, 110, 0.3)',
    marginHorizontal: 8,
  },
  scrollIndicator: {
    alignItems: 'center',
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(15, 118, 110, 0.2)',
    width: '100%',
  },
  scrollText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#0F766E',
    marginTop: 4,
  },
});
