import { StyleSheet, Platform } from 'react-native';

/**
 * Create responsive styles based on current screen dimensions
 * This function is called on every render with fresh dimensions from useWindowDimensions
 */
export const createStyles = (SCREEN_WIDTH: number, isTablet: boolean) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F9FAFB',
      maxHeight: isTablet ? '92%' : undefined,
    },
    header: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
      paddingTop: isTablet ? 20 : (Platform.OS === 'ios' ? 40 : 12),
      paddingBottom: isTablet ? 8 : 10,
      backgroundColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
    },
    headerContent: {
      alignItems: 'center',
    },
    headerTitle: {
      fontSize: isTablet ? 20 : 22,
      fontWeight: '800',
      color: '#111827',
      textAlign: 'center',
    },
    headerSubtitle: {
      fontSize: isTablet ? 12 : 13,
      color: '#6B7280',
      marginTop: 2,
      textAlign: 'center',
    },
    toggleSection: {
      backgroundColor: '#FFFFFF',
      paddingVertical: isTablet ? 8 : 10,
      paddingHorizontal: 24,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
    },
    toggleContainer: {
      flexDirection: 'row',
      backgroundColor: '#F3F4F6',
      borderRadius: 12,
      padding: 4,
    },
    toggleOption: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      borderRadius: 10,
      position: 'relative',
    },
    toggleOptionActive: {
      backgroundColor: '#FFFFFF',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.1,
      shadowRadius: 3,
      elevation: 2,
    },
    toggleOptionText: {
      fontSize: 15,
      fontWeight: '600',
      color: '#6B7280',
    },
    toggleOptionTextActive: {
      color: '#111827',
      fontWeight: '700',
    },
    savingsBadge: {
      position: 'absolute',
      top: -8,
      right: 8,
      backgroundColor: '#10B981',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 8,
    },
    savingsBadgeText: {
      fontSize: 10,
      fontWeight: '800',
      color: '#FFFFFF',
    },
    carouselContent: {
      paddingVertical: isTablet ? 8 : 10,
    },
    carouselContentTablet: {
      flexDirection: 'row',
      justifyContent: 'center',
      paddingHorizontal: SCREEN_WIDTH < 400 ? 16 : 40,
    },
    planCard: {
      width: isTablet
        ? SCREEN_WIDTH * 0.45
        : SCREEN_WIDTH < 400
          ? SCREEN_WIDTH - 32
          : SCREEN_WIDTH - 60,
      backgroundColor: '#FFFFFF',
      borderRadius: 24,
      padding: isTablet ? 12 : (SCREEN_WIDTH < 400 ? 14 : 16),
      marginHorizontal: (isTablet ? 30 : (SCREEN_WIDTH < 400 ? 16 : 20)) / 2,
      borderWidth: 2,
      borderColor: '#E5E7EB',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 4,
    },
    planCardPopular: {
      borderColor: '#4ECFBF',
      borderWidth: 3,
      backgroundColor: '#FFFFFF',
    },
    popularBadge: {
      position: 'absolute',
      top: -12,
      left: 24,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#4ECFBF',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      shadowColor: '#4ECFBF',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    popularBadgeText: {
      fontSize: 11,
      fontWeight: '800',
      color: '#FFFFFF',
      marginLeft: 4,
      letterSpacing: 0.5,
    },
    planHeader: {
      marginBottom: isTablet ? 4 : 6,
    },
    planName: {
      fontSize: isTablet ? 20 : 22,
      fontWeight: '800',
      color: '#111827',
      marginBottom: 2,
    },
    planDescription: {
      fontSize: isTablet ? 12 : 13,
      color: '#6B7280',
    },
    highlightContainer: {
      backgroundColor: '#FEF3C7',
      paddingHorizontal: 10,
      paddingVertical: isTablet ? 3 : 4,
      borderRadius: 10,
      marginBottom: isTablet ? 4 : 6,
      alignSelf: 'flex-start',
    },
    highlightText: {
      fontSize: isTablet ? 12 : 13,
      fontWeight: '700',
      color: '#D97706',
    },
    pricingContainer: {
      alignItems: 'center',
      paddingVertical: isTablet ? 8 : 10,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: '#F3F4F6',
      marginBottom: isTablet ? 8 : 10,
    },
    priceRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
    },
    price: {
      fontSize: isTablet ? 32 : (SCREEN_WIDTH < 400 ? 32 : 38),
      fontWeight: '900',
      color: '#111827',
      letterSpacing: -1,
    },
    pricePeriod: {
      fontSize: 15,
      color: '#6B7280',
      marginLeft: 4,
      fontWeight: '600',
    },
    monthlyEquivalent: {
      fontSize: isTablet ? 13 : 14,
      color: '#10B981',
      fontWeight: '700',
      marginTop: isTablet ? 3 : 4,
    },
    savingsTag: {
      backgroundColor: '#D1FAE5',
      paddingHorizontal: 10,
      paddingVertical: isTablet ? 3 : 4,
      borderRadius: 10,
      marginTop: isTablet ? 4 : 6,
    },
    savingsText: {
      fontSize: isTablet ? 11 : 12,
      fontWeight: '800',
      color: '#059669',
    },
    featuresGrid: {
      marginBottom: isTablet ? 10 : 14,
      gap: isTablet ? 6 : 8,
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    featureIconContainer: {
      width: isTablet ? 24 : 28,
      height: isTablet ? 24 : 28,
      borderRadius: isTablet ? 12 : 14,
      backgroundColor: '#F0FDFA',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: isTablet ? 6 : 8,
    },
    featureText: {
      flex: 1,
      fontSize: isTablet ? 11 : 12.5,
      fontWeight: '600',
      color: '#374151',
    },
    ctaButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
      borderWidth: 2,
      borderColor: '#4ECFBF',
      paddingVertical: isTablet ? 10 : 12,
      borderRadius: 14,
      shadowColor: '#4ECFBF',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 3,
    },
    ctaButtonPopular: {
      backgroundColor: '#4ECFBF',
      borderColor: '#4ECFBF',
    },
    ctaButtonText: {
      fontSize: isTablet ? 14 : 16,
      fontWeight: '800',
      color: '#4ECFBF',
      marginRight: 8,
    },
    ctaButtonTextPopular: {
      color: '#FFFFFF',
    },
    paginationContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: isTablet ? 8 : 10,
    },
    paginationDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#D1D5DB',
      marginHorizontal: 4,
    },
    paginationDotActive: {
      backgroundColor: '#4ECFBF',
      width: 24,
    },
    footer: {
      backgroundColor: '#FFFFFF',
      paddingTop: isTablet ? 6 : 8,
      paddingHorizontal: 20,
      paddingBottom: isTablet ? 12 : (Platform.OS === 'ios' ? 24 : 8),
      borderTopWidth: 1,
      borderTopColor: '#E5E7EB',
    },
    footerInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: isTablet ? 6 : 8,
      gap: 16,
    },
    footerInfoItem: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    footerInfoText: {
      fontSize: 11,
      color: '#6B7280',
      marginLeft: 4,
      fontWeight: '500',
    },
    legalLinksContainer: {
      backgroundColor: '#F9FAFB',
      paddingVertical: isTablet ? 8 : 10,
      paddingHorizontal: 12,
      marginTop: isTablet ? 4 : 6,
      marginBottom: isTablet ? 4 : 6,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    legalLinksHeader: {
      fontSize: 10,
      fontWeight: '600',
      color: '#6B7280',
      textAlign: 'center',
      marginBottom: 5,
      letterSpacing: 0.5,
    },
    legalLinks: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    legalLinkText: {
      fontSize: isTablet ? 13 : 14,
      color: '#4ECFBF',
      textDecorationLine: 'underline',
      fontWeight: '700',
    },
    legalSeparator: {
      fontSize: 14,
      color: '#9CA3AF',
      marginHorizontal: 10,
      fontWeight: '600',
    },
    maybeLaterButton: {
      paddingVertical: isTablet ? 4 : 6,
      alignItems: 'center',
      marginTop: 2,
    },
    maybeLaterText: {
      fontSize: isTablet ? 14 : 15,
      color: '#9CA3AF',
      fontWeight: '600',
    },
  });
};
